#!/bin/sh
# Since Sublime is fucking insane and can't handle symlinks for the User
# directory, we'll need to manually copy stuff over.

rm -rf $MY_ZSH/sublime3/User

if [ "$(uname -s)" == "Darwin" ]
	sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 3/Packages
else
	sublime_dir=~/.config/sublime-text-3/Packages
fi

cp -R ${sublime_dir}/User $MY_ZSH/sublime3/User
